<?php

namespace Akredytacja\AttendeeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Att2GadzetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Att2GadzetRepository extends EntityRepository
{
}
