<?php

namespace Akredytacja\AttendeeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Att2UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Att2UserRepository extends EntityRepository
{
    public function findUserInvitations( $idUsera )
    {
        $query = $this -> getEntityManager()
                -> createQuery(
                        'SELECT a2u FROM AkredytacjaAttendeeBundle:Att2user a2u '
                        .' INNER JOIN a2u.attendee a '
                        .' INNER JOIN a.user u '
//                        .' INNER JOIN a.tempUser tp '
                        .' WHERE u.id = :idUsera'
//                        . ' OR tp.id = :idUsera'
                )
                -> setParameter( 'idUsera', $idUsera )
                ;

        try {
            return $query -> getResult();
        } catch (Exception $ex) {
            return null;
        } 
    }
}
