<?php

namespace ContactBookBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactBookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactBookRepository extends EntityRepository
{
//    public function findAllContacts($page = 1, $sorting = 'ASC', $sortingColumn = 'lastName')
//    {
//        $em = $this->getEntityManager();
//        
//        //Obliczam offset
//        $limit = 20; //Standardowo będzie 20
//        $offset = ($page - 1) * $limit; //Obliczam offset
//        
//        return $em->getRepository( 'ContactBookBundle:ContactBook' ) 
//                -> findBy(array(), array($sortingColumn => $sorting), $limit, $offset);
//        
//    }
}
